# Use postgres/example user/password credentials
version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: blogstrapi
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ~/.PostgressData/blog:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
